version: '3.9'
services:

  # APP
  app:
    container_name: APP
    build: ./.docker/symfony
    ports:
      - "80:8000"
    volumes:
      - ./app:/var/www/app
    networks:
      - overlay

networks:
  overlay: